export const texts = {
  auth: {
    loginTitle: 'Acessar Conta',
    registerTitle: 'Nova Conta',
    emailLabel: 'E-mail:',
    passwordLabel: 'Senha:',
    nameLabel: 'Nome completo:',
    cpfLabel: 'CPF:',
    loginSubmit: 'Entrar',
    loginLoading: 'Entrando...',
    registerSubmit: 'Confirmar Cadastro',
    registerLoading: 'Cadastrando...',
    noAccount: 'Ainda não é paciente?',
    noAccountLink: 'Cadastre-se aqui',
    hasAccount: 'Já possui cadastro?',
    hasAccountLink: 'Faça login pelo painel',
    loginError: 'Não foi possível acessar sua conta. Verifique seus dados.',
    registerError: 'Houve um problema ao criar seu cadastro.',
  },
  dashboard: {
    title: 'Painel de Consultas',
    welcome: 'Bem-vindo(a),',
    logoutBtn: 'Sair',
    patientSectionTitle: 'Agendar Nova Consulta',
    dateLabel: 'Data e Horário:',
    notesLabel: 'Alguma observação importante para o médico? (opcional):',
    scheduleSubmit: 'Confirmar Agendamento',
    scheduleLoading: 'Aguarde...',
    scheduleSuccess: 'Sua consulta foi agendada com sucesso!',
    scheduleError: 'Infelizmente não foi possível agendar este horário.',
    myAppointmentsTitle: 'Minhas Consultas',
    allAppointmentsTitle: 'Todas as Consultas do Sistema',
    loadingAppointments: 'Buscando suas consultas...',
    noAppointments: 'Você ainda não possui consultas agendadas.',
    tablePatient: 'Paciente (Nome / CPF)',
    tableDate: 'Data e Hora',
    tableStatus: 'Situação',
    tableWeather: 'Clima Previsto na Consulta',
    tableActions: 'Ações',
    cancelBtn: 'Cancelar',
    cancelConfirm: 'Tem certeza que deseja cancelar esta consulta?',
  },
  admin: {
    title: 'Painel da Administração',
    welcome: 'Bem-vindo(a),',
    logoutBtn: 'Sair',
    filterStatusLabel: 'Filtrar por Situação:',
    filterDateLabel: 'Data específica:',
    statusAll: 'Todas',
    statusScheduled: 'Agendadas',
    statusConfirmed: 'Confirmadas',
    statusCanceled: 'Canceladas',
    statusCompleted: 'Concluídas',
    loadingAppointments: 'Buscando consultas do sistema...',
    noAppointments: 'Nenhuma consulta encontrada com esses filtros.',
    cancelConfirm: 'Deseja cancelar esta consulta (Ação Administrativa)?'
  }
};
